version: '3.8'

services:
  catalog-service:
    build: ./catalog-service
    container_name: catalog-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/skillbox
    depends_on:
      - mongo
      - payment-service
    networks:
      - skillbox-network
    restart: unless-stopped

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/skillbox
    depends_on:
      - mongo
    networks:
      - skillbox-network
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - skillbox-network
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  skillbox-network:
    driver: bridge

