### Получение списка направлений
GET http://localhost:8082/catalog/directions
Content-Type: application/json

### Получение курсов по направлению
GET http://localhost:8082/catalog/courses/Программирование
Content-Type: application/json

### Получение информации о курсе
GET http://localhost:8082/catalog/course/1
Content-Type: application/json

### Запись пользователя на курс с ВК
POST http://localhost:8082/catalog/enroll/auth-method
Content-Type: application/json

{
  "userId": "2",
  "courseId": "1",
  "method": "vk",
  "tariff": "STARTER"
}

### Запись пользователя на курс с ручным заполнением данных
POST http://localhost:8082/catalog/enroll
Content-Type: application/json

{
  "userId": "2",
  "courseId": "2",
  "name": "Дмитрий Борисович Афанасьев",
  "email": "dima@example.com",
  "tariff": "STARTER"
}

### Создание платежа для пользователя
POST http://localhost:8080/payment/create
Content-Type: application/json

{
  "userId": "2",
  "courseId": "1",
  "tariff": "STARTER",
  "name": "Дмитрий Борисович Афанасьев",
  "email": "dima@example.com"
}

### Выполнение оплаты для пользователя
POST http://localhost:8080/payment/process?userId=2&paymentLink=https://payment-url-example.com/pay&amount=10